spring.application.name=ibe-blits-backend
server.port=${PORT:8081}

# spring.datasource.url=jdbc:postgresql://localhost:5432/ibe
# spring.datasource.username=postgres
# spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ibe}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Anum#2225}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.http.path=/api/graphql
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
app.seed.enabled=${APP_SEED_ENABLED:true}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
